### ISSUE TITLE
[Bug] Widgets not loading correctly

### ISSUE THREAD

**Issue by nayu-codes** [DGh0st/HSWidgets#2]
Everything works rather nicely on iOS 12.1.2 XS Max (compiled for arm64e), but some issues:

1) As mentioned earlier, the Clock widget doesn't seem to display anything when on the homescreen.

2) Widgets that require interaction to start working (Weather, Google calenders etc.) can't initiate 

3) Activity module doesn't seem to load.

A really cool concept though! Really looking forward to seeing more updates :D

**Comment by Nayuta-Kani** [comment]
Ahh, figured out that the clock not loading was due to XenHTML, though the rest is still not fixed I guess

**Comment by DGh0st** [comment]
I am currently working on rewriting HSClockWidget to be more compatible with other tweaks and less buggy on iOS 11+.

I have been aware of XenHTML causing issues with clock widget when you hide/remove it through XenHTML. I don't think I can do much about that from my side but I'll look into it after fixing clock widget, today widgets and other bugs specific to the tweak.

I don't see how

> Widgets that require interaction to start working (Weather, Google calenders etc.) can't initiate
Seems to be the same 

and

> Activity module doesn't seem to load.

are separate issues. Anyways there is plan to potentially rewrite today widgets, though I am not sure how easy/soon that'll be.

Also, if you plan on redistributing the arm64e version, please don't distribute it under the same name (or with me as the maintainer). The reason it hasn't already been done is because the tweak is pretty buggy iOS 11+ so there is really no reason to have A12 devices downloading it as well (not yet).

**Comment by Nayuta-Kani** [comment]
Ahhh I see, thanks for clarifying! I only complied this for personal use cause I found this really interesting :3

Looking forward to the updates haha xD take your time :p

**Comment by DGh0st** [comment]
Revision [60c1bb5](https://github.com/DGh0st/HSWidgets/commit/60c1bb5b54dc3cbd9d18c568cd7c395e70996582) should greatly improve the today widget loading.

The [HSWidgets 0.0.1-5](https://dgh0st.github.io/Files/?p=com.dgh0st.hswidgets) on my repo should now be compiled with arm64e.
